<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="urn:com:supportical:types:PQR"
  xmlns:tns="urn:com:supportical:types:PQR" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:complexType name="PQR_Ciudadano">
    <xsd:annotation>
      <xsd:appinfo source="appian.jpa">@Table(name="Ciudadano")</xsd:appinfo>
      <xsd:appinfo source="http://www.appian.com/ae/types/2009">
        <ns2:Metadata xmlns:ns2="http://www.appian.com/ae/types/2009">
          <ns2:versionUuid>0000ef0b-9314-8000-4fc9-7f0000014e7a</ns2:versionUuid>
          <ns2:history>
            <ns2:historyInfo versionUuid="0000ef0b-9314-8000-4fc9-7f0000014e7a"/>
          </ns2:history>
        </ns2:Metadata>
      </xsd:appinfo>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="idCiudadano" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Id @GeneratedValue @Column(name="idCiudadano", nullable=false, unique=true, columnDefinition="INT IDENTITY")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="idTipoPersona" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="idTipoPersona", columnDefinition="INT") @JoinColumn(name="idTipoPersona")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="idTipoIdentificacion" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="idTipoIdentificacion", columnDefinition="INT") @JoinColumn(name="idTipoIdentificacion")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="NumeroIdentificacion" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="NumeroIdentificacion", columnDefinition="NVARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="idsCondicionesEspeciales" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="idsCondicionesEspeciales", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="idTipoGenero" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="idTipoGenero", columnDefinition="INT") @JoinColumn(name="idTipoGenero")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="CorreoElectronico" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="CorreoElectronico", columnDefinition="NVARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="NumeroTelefonico" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="NumeroTelefonico", columnDefinition="NVARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="idTipoPais" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="idTipoPais", columnDefinition="INT") @JoinColumn(name="idTipoPais")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="idTipoMunicipio" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="idTipoMunicipio", columnDefinition="INT") @JoinColumn(name="idTipoMunicipio")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="PrimerNombre" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="PrimerNombre", columnDefinition="NVARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="SegundoNombre" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="SegundoNombre", columnDefinition="NVARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="PrimerApellido" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="PrimerApellido", columnDefinition="NVARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="SegundoApellido" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="SegundoApellido", columnDefinition="NVARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RazonSocial" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="RazonSocial", columnDefinition="NVARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="FechaExpedicionDocumento" nillable="true" type="xsd:date">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="FechaExpedicionDocumento", columnDefinition="DATE")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="FechaNacimiento" nillable="true" type="xsd:date">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="FechaNacimiento", columnDefinition="DATE")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="SYNC" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="SYNC", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
