<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="urn:com:supportical:types:PQR"
  xmlns:tns="urn:com:supportical:types:PQR" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:complexType name="PQR_TipoEtiqueta">
    <xsd:annotation>
      <xsd:appinfo source="appian.jpa">@Table(name="TipoEtiqueta")</xsd:appinfo>
      <xsd:appinfo source="http://www.appian.com/ae/types/2009">
        <ns2:Metadata xmlns:ns2="http://www.appian.com/ae/types/2009">
          <ns2:versionUuid>0000ef0b-9fca-8000-4fd1-7f0000014e7a</ns2:versionUuid>
          <ns2:history>
            <ns2:historyInfo versionUuid="0000ef0b-9fca-8000-4fd1-7f0000014e7a"/>
          </ns2:history>
        </ns2:Metadata>
      </xsd:appinfo>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="idTipoEtiqueta" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Id @GeneratedValue @Column(name="idTipoEtiqueta", nullable=false, unique=true, columnDefinition="INT IDENTITY")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="Nombre" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="Nombre", nullable=false, columnDefinition="NVARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="Codigo" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="Codigo", nullable=false, columnDefinition="NVARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="Icono" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="Icono", columnDefinition="NVARCHAR(15)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="Color" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="Color", columnDefinition="NVARCHAR(10)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="idTipoCategoriaEtiqueta" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="idTipoCategoriaEtiqueta", columnDefinition="INT") @JoinColumn(name="idTipoCategoriaEtiqueta")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="Activo" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="Activo", nullable=false, columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
