<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="urn:com:appian:types:PQR"
  xmlns:tns="urn:com:appian:types:PQR" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:complexType name="PQR_CDT_expediente">
    <xsd:annotation>
      <xsd:appinfo source="http://www.appian.com/ae/types/2009">
        <ns2:Metadata xmlns:ns2="http://www.appian.com/ae/types/2009">
          <ns2:versionUuid>0001efc1-ab16-8000-c861-7f0000014e7a</ns2:versionUuid>
          <ns2:history>
            <ns2:historyInfo versionUuid="0001efc1-ab16-8000-c861-7f0000014e7a"/>
          </ns2:history>
        </ns2:Metadata>
      </xsd:appinfo>
      <xsd:documentation><![CDATA[Contiene los expedientes creados en SGDA]]></xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="Id" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Id @GeneratedValue</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="TrdId" nillable="true" type="xsd:int"/>
      <xsd:element name="TrdVersionId" nillable="true" type="xsd:int"/>
      <xsd:element name="IdExpediente" nillable="true" type="xsd:int"/>
      <xsd:element name="NumeroExpediente" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(length=255)</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="NombreFolder" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(length=255)</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="fechaCreacion" nillable="true" type="xsd:date"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
