<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="urn:com:appian:types:PQR"
  xmlns:tns="urn:com:appian:types:PQR" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:complexType name="PQR_CDT_AITokens">
    <xsd:annotation>
      <xsd:appinfo source="http://www.appian.com/ae/types/2009">
        <ns2:Metadata xmlns:ns2="http://www.appian.com/ae/types/2009">
          <ns2:versionUuid>0000efae-0f9b-8000-c4f6-7f0000014e7a</ns2:versionUuid>
          <ns2:history>
            <ns2:historyInfo versionUuid="0000efae-0f9b-8000-c4f6-7f0000014e7a"/>
          </ns2:history>
        </ns2:Metadata>
      </xsd:appinfo>
      <xsd:documentation><![CDATA[Campos para mostrar datos estadísticos de los tokens]]></xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="id" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Id @GeneratedValue</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="inputTokens" nillable="true" type="xsd:int"/>
      <xsd:element name="outputTokens" nillable="true" type="xsd:int"/>
      <xsd:element name="fecha" nillable="true" type="xsd:dateTime"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
